"""
SafeMAPS — Blackspot Mapper

Imports Bangalore accident blackspot data into PostGIS.
Run this AFTER osm_loader.py (needs road_segments to exist for snapping).

Usage:
    # Default: real BTP/OpenCity station-level data
    # (data/btp_station_blackspots.csv, built by btp_station_importer.py):
    python blackspot_mapper.py

    # Use a different CSV (format: lat,lon,severity,total_accidents,fatal_accidents,description):
    python blackspot_mapper.py --csv /path/to/blackspots.csv

    # Optional CSV column:
    #   severity_weight - numeric 0..10 risk weight, used instead of tier default

    # Clear existing data before importing:
    python blackspot_mapper.py --clear

Phase 1 fix vs original:
    - Uses INSERT ... ON CONFLICT DO NOTHING so re-running is safe
    - Snapping failure (empty road_segments) now shows a clear error
      instead of silently inserting NULL nearest_edge_id
    - Added --clear flag for clean reimports

Phase 2 (real data):
    - Removed the hand-written BUILT_IN_BLACKSPOTS placeholder list.
      Default source is now data/btp_station_blackspots.csv — real BTP
      crash counts via OpenCity, produced by btp_station_importer.py.
      See BTP_README.md for how that CSV is built and its known limits
      (station-jurisdiction resolution, not per-crash coordinates).
"""

import sys
import asyncio
import csv
import logging
import argparse
from pathlib import Path

import asyncpg

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
logger = logging.getLogger(__name__)

backend_dir = Path(__file__).resolve().parent.parent / "backend"
if backend_dir.exists():
    sys.path.insert(0, str(backend_dir))
else:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import settings

SEVERITY_WEIGHTS = {
    "low": 1.0,
    "moderate": 3.0,
    "high": 6.0,
    "critical": 10.0,
}

# Default source: real BTP/OpenCity station-level crash data.
# Generated by btp_station_importer.py — run that first if this is missing.
DEFAULT_CSV = Path(__file__).resolve().parent / "data" / "btp_station_blackspots.csv"


async def clear_blackspots(conn: asyncpg.Connection) -> None:
    count = await conn.fetchval("SELECT COUNT(*) FROM accident_blackspots;")
    await conn.execute("DELETE FROM accident_blackspots;")
    logger.info(f"Cleared {count} existing blackspots.")


async def check_road_segments(conn: asyncpg.Connection) -> bool:
    count = await conn.fetchval("SELECT COUNT(*) FROM road_segments;")
    if count == 0:
        logger.error(
            "road_segments table is empty. "
            "Run osm_loader.py first before importing blackspots."
        )
        return False
    logger.info(f"road_segments has {count:,} segments — snapping will work.")
    return True


async def load_from_csv(csv_path: Path) -> list[tuple]:
    records = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader, 1):
            try:
                severity = row.get("severity", "moderate").lower().strip()
                severity_weight = row.get("severity_weight", "").strip()
                weight = (
                    float(severity_weight)
                    if severity_weight
                    else SEVERITY_WEIGHTS.get(severity, SEVERITY_WEIGHTS["moderate"])
                )
                records.append((
                    float(row["lat"]),
                    float(row["lon"]),
                    severity,
                    weight,
                    int(row.get("total_accidents", 0)),
                    int(row.get("fatal_accidents", 0)),
                    row.get("description", ""),
                ))
            except (ValueError, KeyError) as exc:
                logger.warning(f"Skipping CSV row {i}: {exc}")
    logger.info(f"Loaded {len(records)} records from {csv_path}.")
    return records


async def snap_and_insert(conn: asyncpg.Connection, blackspots: list[tuple]) -> int:
    """
    Insert blackspots, snapping each to the nearest road segment.
    Uses ON CONFLICT DO NOTHING so re-running is safe.
    """
    inserted = 0
    skipped = 0

    for record in blackspots:
        if len(record) == 7:
            lat, lon, severity, weight, total, fatal, desc = record
        else:
            lat, lon, severity, total, fatal, desc = record
            weight = None

        if severity not in SEVERITY_WEIGHTS:
            severity = "moderate"
        if weight is None:
            weight = SEVERITY_WEIGHTS[severity]
        weight = max(0.0, min(float(weight), 10.0))

        # Snap to nearest road segment
        nearest_edge = await conn.fetchval("""
            SELECT id FROM road_segments
            ORDER BY geom <-> ST_SetSRID(ST_MakePoint($1, $2), 4326)
            LIMIT 1;
        """, lon, lat)

        if nearest_edge is None:
            logger.warning(f"No road segment found near ({lat}, {lon}) — skipping.")
            skipped += 1
            continue

        try:
            await conn.execute("""
                INSERT INTO accident_blackspots
                    (severity, severity_weight, total_accidents, fatal_accidents,
                     description, nearest_edge_id, geom)
                VALUES ($1, $2, $3, $4, $5, $6,
                        ST_SetSRID(ST_MakePoint($7, $8), 4326))
            """,
                severity, weight, total, fatal, desc, nearest_edge,
                lon, lat,
            )
            inserted += 1
        except Exception as exc:
            logger.warning(f"Insert failed for ({lat}, {lon}): {exc}")
            skipped += 1

    logger.info(f"Inserted {inserted} blackspots, skipped {skipped}.")
    return inserted


async def main():
    parser = argparse.ArgumentParser(description="Import Bangalore accident blackspot data")
    parser.add_argument("--csv", type=str, help="Path to CSV file")
    parser.add_argument(
        "--clear", action="store_true",
        help="Clear existing blackspot data before importing",
    )
    args = parser.parse_args()

    conn = await asyncpg.connect(
        host=settings.postgres_host,
        port=settings.postgres_port,
        database=settings.postgres_db,
        user=settings.postgres_user,
        password=settings.postgres_password,
    )

    try:
        if not await check_road_segments(conn):
            sys.exit(1)

        if args.clear:
            await clear_blackspots(conn)

        if args.csv:
            csv_path = Path(args.csv)
        else:
            csv_path = DEFAULT_CSV
            if not csv_path.exists():
                logger.error(
                    f"No CSV at {csv_path} and no --csv given. "
                    "Generate the real BTP dataset first:\n"
                    "  python btp_station_importer.py\n"
                    "or pass your own with --csv /path/to/blackspots.csv"
                )
                sys.exit(1)
            logger.info(f"Using real BTP station data: {csv_path}")

        blackspots = await load_from_csv(csv_path)

        count = await snap_and_insert(conn, blackspots)
        logger.info(f"Blackspot import complete: {count} records inserted.")

    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
