-- ============================================================
-- SafeMAPS — Phase 6 Schema Migration
-- Green Score & Trip History
--
-- Run after migration_phase5.sql:
--   psql -h localhost -U healthroute -d healthroute -f migration_phase6.sql
-- ============================================================

-- ── trip_history ──────────────────────────────────────────────────────
-- One row per completed route. Stores both the chosen route metrics
-- AND the fastest-route baseline so Green Score can compute the delta.
-- session_id is an anonymous UUID generated by the frontend on first
-- visit and persisted in localStorage — no auth required.

CREATE TABLE IF NOT EXISTS trip_history (
    id                      BIGSERIAL PRIMARY KEY,
    session_id              TEXT        NOT NULL,

    -- Route endpoints
    origin_lat              DOUBLE PRECISION NOT NULL,
    origin_lon              DOUBLE PRECISION NOT NULL,
    dest_lat                DOUBLE PRECISION NOT NULL,
    dest_lon                DOUBLE PRECISION NOT NULL,

    -- Chosen route metrics
    profile                 TEXT        NOT NULL,
    distance_km             DOUBLE PRECISION NOT NULL,
    travel_time_min         DOUBLE PRECISION NOT NULL,
    avg_aqi                 DOUBLE PRECISION NOT NULL,
    aqi_exposure_integral   DOUBLE PRECISION NOT NULL, -- Σ(AQI × time_min) per edge
    hotspots_passed         INT         NOT NULL DEFAULT 0,

    -- Fastest route baseline (always computed for comparison)
    baseline_time_min       DOUBLE PRECISION NOT NULL,
    baseline_aqi_integral   DOUBLE PRECISION NOT NULL,
    baseline_hotspots       INT         NOT NULL DEFAULT 0,

    -- Pre-computed Green Score deltas (stored for fast aggregation)
    time_delta_min          DOUBLE PRECISION GENERATED ALWAYS AS
                                (baseline_time_min - travel_time_min) STORED,
    aqi_integral_saved      DOUBLE PRECISION GENERATED ALWAYS AS
                                (baseline_aqi_integral - aqi_exposure_integral) STORED,
    hotspots_avoided        INT GENERATED ALWAYS AS
                                (baseline_hotspots - hotspots_passed) STORED,

    -- Estimated PM2.5 avoided in micrograms
    -- Formula: AQI_integral_saved × 0.0025 g/min × 1000 µg/g
    pm25_ug_avoided         DOUBLE PRECISION GENERATED ALWAYS AS
                                ((baseline_aqi_integral - aqi_exposure_integral) * 2.5) STORED,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trip_history_session
    ON trip_history (session_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_trip_history_created
    ON trip_history (created_at DESC);


-- ── green_score_cache ─────────────────────────────────────────────────
-- Pre-aggregated monthly Green Score per session.
-- Recomputed on every new trip write (via the backend).
-- Avoids expensive aggregation on every /api/user/green-score GET.

CREATE TABLE IF NOT EXISTS green_score_cache (
    id              BIGSERIAL PRIMARY KEY,
    session_id      TEXT        NOT NULL UNIQUE,
    month           DATE        NOT NULL,  -- first day of the month

    -- Aggregated stats
    total_trips     INT         NOT NULL DEFAULT 0,
    total_km        DOUBLE PRECISION NOT NULL DEFAULT 0,
    aqi_saved_total DOUBLE PRECISION NOT NULL DEFAULT 0,
    pm25_ug_saved   DOUBLE PRECISION NOT NULL DEFAULT 0,
    hotspots_avoided INT        NOT NULL DEFAULT 0,
    time_delta_min  DOUBLE PRECISION NOT NULL DEFAULT 0,

    -- Green Score 0–100
    green_score     DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_green_score_session
    ON green_score_cache (session_id, month DESC);
